### ISSUE TITLE
Parse a WAV file

### ISSUE THREAD

**Issue by kmfarley11** [kmfarley11/8Bitify#1]
Given a .wav file (can hardcode for now) deconstruct the contents by parsing metadata into simple variables, and the raw audio data into a python list.

Note: we may be able to use the standard file operations libraries to read / write, but if easier we could certainly use pysox to expedite the processing and development

**Comment by okeltw** [comment]
@kmfarley11 Found SciPy Functions for parsing a .wav

I found free .wav files for use (we may need to cite the source)

**Comment by kmfarley11** [comment]
http://pysoundfile.readthedocs.io/en/0.9.0/ makes this ridiculously easy...

I originally was trying to use scipy and / or wave; however, scipy didn't support 24bit wav and wave required a lot more work / time than is really necessary

the soundfile lib requires a few packages and pip things, i'll post instructions in the readme soon

**Comment by kmfarley11** [comment]
seems to be done
