### ISSUE TITLE
Integrate numpy

### ISSUE THREAD

**Issue by kmfarley11** [kmfarley11/8Bitify#2]
We will use the 3rd party lib numpy to run matrix operations against the raw audio data. This will allow us to experiment on audio wave modifications as well as run simple operations against all the data at once.

For this issue, write up simple instructions to install numpy, import it into the main program file, and write a function to convert a python list into our desired numpy alternative (a numpy array). Finally, begin research on how to force a range of values into a smaller range of 8-bits (likely will use numpy's where() functionality).

**Comment by okeltw** [comment]
SciPy/NumPy added to requirements.txt

**Comment by kmfarley11** [comment]
we should use this issue to make an "installation" section in our front Readme.md. This section can include instructions to install pip / numpy and maybe scipy, doesn't need anything crazy

**Comment by okeltw** [comment]
Based on other packages, I think it is safe to assume the "user" is familiar with pip. We should include a line in the Readme, but I think that it could be as simple as 

> RUN `pip3 install -r requirements.txt`

**Comment by kmfarley11** [comment]
seems to be done, just make sure readme and requirements are kept up to date
