### ISSUE TITLE
Enable 8Bitify

### ISSUE THREAD

**Issue by kmfarley11** [kmfarley11/8Bitify#5]
Write the necessary code to modify raw audio data such that the range of values is forced into an 8-bit resolution. 

Note: #1 should produce the desired raw data to be worked with, then #2 should enable array / matrix operations. This program will then properly discretize the data and use #4 to package a new .wav file. Finally, #3 will allow us to show the user the result of the modifications.

**Comment by okeltw** [comment]
#3 failed; see #7 instead

**Comment by kmfarley11** [comment]
implemented, notice that if the range of values is very small then this has a lot less effect... consider investigating a chiptunify / fixing this to adjust frequency or tonality as well

**Comment by kmfarley11** [comment]
done, but isn't exactly what we hoped for. what we were considering was more of a chiptunify type thing. Which extends beyond the scope of a two week project. Thus, closing this issue. To experiment with chiptunify / instrument extrapolation, create a new issue.
