### ISSUE TITLE
Find Replacement for Snack

### ISSUE THREAD

**Issue by okeltw** [kmfarley11/8Bitify#7]
#3 Integrate Snack: Failed, due to a dead project.
Find a suitable replacement library that can play audio files.

**Comment by okeltw** [comment]
@kmfarley11 can you test this with your NumPy arrays?

https://python-sounddevice.readthedocs.io/en/0.3.7/#playback

**Comment by kmfarley11** [comment]
Since i'm using a ubuntu bash in windows, i can't install the module (no direct access to hardware). We can test this out tomorrow if you'd like to meet up. I'll be good between 11:00am and 12:30pm

**Comment by kmfarley11** [comment]
seems to work, we will use sounddevice, make sure requirements and readme get updated soon
