### ISSUE TITLE
Set Up Argument Parsing

### ISSUE THREAD

**Issue by kmfarley11** [kmfarley11/8Bitify#8]
Doesn't quite matter how we do this, essentially the program will be run with various parameters to navigate to various functions. This issue will stub the argument parsing so that we will be ready to support various experiments, mainly just need to be able to default the flow for 8Bitify functions.

**Comment by kmfarley11** [comment]
seems good for now, will keep this issue open as with more functionality, more args will be parsed / added

**Comment by okeltw** [comment]
Now that there are options to interface with, I will finish this up.

I should also add an option to include two+WAV files for superimposition/convolution etc...will sound like shit, but the purpose is experimentation anways.

**Comment by kmfarley11** [comment]
cool, as a side note with my latest push to master eight_bitify now can take a parameter (bits=) to customize the bitified resolution, so for experiments we could have some arg that does that as well if desired

**Comment by kmfarley11** [comment]
this is done up to current experiments available, add more parsing as necessary for new experiments
